// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMDnOgF8Uq1knNmkqIJC32xzfrc2BhJ4',
    appId: '1:781682431136:web:d9e902c9de70632d3da5c5',
    messagingSenderId: '781682431136',
    projectId: 'vahan-serv',
    authDomain: 'vahan-serv.firebaseapp.com',
    storageBucket: 'vahan-serv.firebasestorage.app',
    measurementId: 'G-Z0W62L71BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKkfE2fQSZvqrLYmkabZj_vWcZzsWPN8',
    appId: '1:781682431136:android:4e3d19cdc445edf63da5c5',
    messagingSenderId: '781682431136',
    projectId: 'vahan-serv',
    storageBucket: 'vahan-serv.firebasestorage.app',
  );
}
